### PR TITLE
closes #13 Refresh Pod list in endless loop to tail all pod's logs

### LINKED ISSUE #13: Watch second pod log when the first pod is failed
Kubernetes jobs retry after the first pod is failed. But kube-job can not watch the log of second, or third pod. It can see only the first pod.

### PR DESCRIPTION
**Pull request by h3poteto**

### CODE REVIEW

File: job/watcher.go [hunk 1]
```diff
@@ -33,72 +34,105 @@ func NewWatcher(client *kubernetes.Clientset, container string) *Watcher {
...
+		LabelSelector: labels,
+	}
+	podList, err := w.client.CoreV1().Pods(job.Namespace).List(listOptions)
+	if err != nil {
+		return []corev1.Pod{}, err
+	}
+	return podList.Items, err
+}
+
+// WaitToStartPods wait until starting the pod.
```
Comment (h3poteto) [inline job/watcher.go]: __[Golint]__ comment on exported method Watcher.WaitToStartPod should be of the form "WaitToStartPod ..." ([link](https://sider.review/gh/repos/169710725/pulls/15#issue-3828089))

<sub>posted by Sider</sub>

File: job/watcher.go [hunk 2]
```diff
@@ -33,72 +34,105 @@ func NewWatcher(client *kubernetes.Clientset, container string) *Watcher {
...
+
+		time.Sleep(1 * time.Second)
+		currentPodList = newPodList
+		continue retry
 	}
+	return nil
+}
 
+// WatchPods gets wait to start pod and tail the logs.
+func (w *Watcher) WatchPods(pods []corev1.Pod, ctx context.Context) error {
```
Comment (h3poteto) [inline job/watcher.go]: __[Golint]__ context.Context should be the first parameter of a function ([link](https://sider.review/gh/repos/169710725/pulls/15#issue-3828088))

<sub>posted by Sider</sub>
