### PR TITLE
closes #24 Add option to clean up all job and pods after completed

### LINKED ISSUE #24: Add option to cleanup all job.
I want to remove all jobs whether job is succeeded or failed.

### PR DESCRIPTION
**Pull request by h3poteto**
I change `cleanup` option. For example:

```
Usage:
  kube-job run [flags]

Flags:
      --args string            Command which you want to run
      --cleanup string         Cleanup completed job after run the job. You can specify 'all', 'succeeded' or 'failed'. (default "succeeded")
      --container string       Container name which you want watch the log
  -h, --help                   help for run
  -f, --template-file string   Job template file
  -t, --timeout int            Timeout seconds

Global Flags:
      --config KUBECONFIG   Kubernetes config file path (If you don't set it, use environment variables KUBECONFIG)
  -v, --verbose             Enable verbose mode
```

### CODE REVIEW

File: job/runner.go [hunk 1]
```diff
@@ -79,3 +91,14 @@ func (j *Job) Run() error {
 	cancel()
 	return err
 }
+
+// Run a command and clean up jobs and pods.
```
Comment (h3poteto) [inline job/runner.go]: __[Golint]__ comment on exported method Job.RunAndCleanup should be of the form "RunAndCleanup ..." ([link](https://sider.review/gh/repos/169710725/pulls/25#issue-4259316))

<sub>posted by Sider</sub>

File: cmd/run.go [hunk 2]
```diff
@@ -40,17 +41,19 @@ func (r *runJob) run(cmd *cobra.Command, args []string) {
 	if !verbose {
 		log.SetLevel(log.WarnLevel)
 	}
+	if r.cleanup != job.All.String() && r.cleanup != job.Succeeded.String() && r.cleanup != job.Failed.String() {
+		err := errors.New("Please set 'all', 'succeeded' or 'failed' as --cleanup.")
```
Comment (h3poteto) [inline cmd/run.go]: __[Golint]__ error strings should not be capitalized or end with punctuation or a newline ([link](https://sider.review/gh/repos/169710725/pulls/25#issue-4259313))

<sub>posted by Sider</sub>

File: job/runner.go [hunk 3]
```diff
@@ -53,6 +53,18 @@ import (
 	log "github.com/sirupsen/logrus"
 )
 
+type CleanupType int
```
Comment (h3poteto) [inline job/runner.go]: __[Golint]__ exported type CleanupType should have comment or be unexported ([link](https://sider.review/gh/repos/169710725/pulls/25#issue-4259314))

<sub>posted by Sider</sub>

File: job/runner.go [hunk 4]
```diff
@@ -53,6 +53,18 @@ import (
...
+
+const (
+	All CleanupType = iota
```
Comment (h3poteto) [inline job/runner.go]: __[Golint]__ exported const All should have comment (or a comment on this block) or be unexported ([link](https://sider.review/gh/repos/169710725/pulls/25#issue-4259315))

<sub>posted by Sider</sub>

File: job/runner.go [hunk 5]
```diff
@@ -79,3 +93,14 @@ func (j *Job) Run() error {
 	cancel()
 	return err
 }
+
+// RunAnd Cleanup executes a command and clean up the job and pods.
```
Comment (h3poteto) [inline job/runner.go]: __[Golint]__ comment on exported method Job.RunAndCleanup should be of the form "RunAndCleanup ..." ([link](https://sider.review/gh/repos/169710725/pulls/25#issue-4259319))

<sub>posted by Sider</sub>

File: cmd/run.go [hunk 6]
```diff
@@ -40,17 +41,19 @@ func (r *runJob) run(cmd *cobra.Command, args []string) {
 	if !verbose {
 		log.SetLevel(log.WarnLevel)
 	}
+	if r.cleanup != job.All.String() && r.cleanup != job.Succeeded.String() && r.cleanup != job.Failed.String() {
+		err := errors.New("please set 'all', 'succeeded' or 'failed' as --cleanup.")
```
Comment (h3poteto) [inline cmd/run.go]: __[Golint]__ error strings should not be capitalized or end with punctuation or a newline ([link](https://sider.review/gh/repos/169710725/pulls/25#issue-4259317))

<sub>posted by Sider</sub>

File: job/runner.go [hunk 7]
```diff
@@ -53,6 +53,20 @@ import (
 	log "github.com/sirupsen/logrus"
 )
 
+// CleanupType for enum.
+type CleanupType int
+
+const (
+	// All is a clean up type
+	All CleanupType = iota
+	Succeeded
```
Comment (h3poteto) [inline job/runner.go]: __[Golint]__ exported const Succeeded should have comment (or a comment on this block) or be unexported ([link](https://sider.review/gh/repos/169710725/pulls/25#issue-4259318))

<sub>posted by Sider</sub>
